# Site settings
title: De Eindhovense Hackerspace
url: "https://madspace.nl"

description: MADspace. De eerste officiÃ«le hackerspace in Eindhoven. Opgericht op 25 juli 2013 te Eindhoven.
keywords: stichting, madspace, foundation, home, hackerspace, eindhoven, bestuur, koen aben, huub de beer, joost hoeks, tom geelen, joris peels, contact

# Build settings
markdown: kramdown

collections:
  projects:
    output: true
